stages:
  - process

process_script:
  stage: process
  script:
    # checkout
    - git checkout main
    - git pull origin main 
    # install dependencies
    - python --version  # Check Python version
    - pip install -r sources\script\requirements.txt
    # run
    - [[-z $(git branch -l ood) ]] && git checkout -b ood || git checkout ood
    - python sources\script\generate_app.py sources\config .
    # push
    - git add .  # Stage changes
    - git status
    - git commit -m "build"
    - git push -u origin ood  # Push to the target branch
  only:
    - main  # Trigger the pipeline only on main branch updates