stages:
  - process

process_script:
  stage: process
  script:
    # checkout
    - git checkout main
    - git pull origin main
    - "[[ -z $(git branch -d ood) ]] && git branch -D ood"
    - git checkout -b ood
    - git remote set-url origin ${CI_REPOSITORY_URL}
    # install dependencies
    - python3 --version  # Check Python version
    - pip3 install -r sources/script/requirements.txt
    # Run
    - python3 sources/script/generate_app.py sources/config .
    # push
    - git status
    - git add .  # Stage changes
    - git status
    - git remote -v
    - git commit -m "build"
    - git push --set-upstream origin ood
  only:
    - main  # Trigger the pipeline only on main branch updates