stages:
  - process

process_script:
  stage: process
  script:
    # checkout
    - git checkout main
    - git pull origin main
    # install dependencies
    - python3 --version  # Check Python version
    - pip3 install -r sources/script/requirements.txt
    # Run
    - python3 sources/script/generate_app.py sources/config .
    # Push
    - git push
  artifacts:
     paths: 
      - "./"
  only:
    - main  # Trigger the pipeline only on main branch updates