stages:
  - process

process_script:
  stage: process
  script:
    # checkout
    - git checkout main
    - git pull origin main 
    # install dependencies
    - python --version  # Check Python version
    - pip install -r sources\script\requirements.txt
    # run
    - python sources\script\generate_app.py sources\config .
    # push
    - git remote add origin ${CI_REPOSITORY_URL}
    - git checkout -b ood  # Create or switch to the target branch
    - git add .  # Stage changes
    - git commit -m "build"
    - git push -u origin ood  # Push to the target branch
  only:
    - main  # Trigger the pipeline only on main branch updates