## 
## hackademia
## 


application:
  # My app name
  name: fmriprep
  # My app version (x.y.z)
  version: 
  # short description
  description: "fMRIprep."
  app:
    # image or module
    type: image
    # image path or module
    image:  docker://nipreps/fmriprep:24.1.1
    # cmd to launch in the container (empty if default)
    cmd: 
    # args (ruby format)
    args: "#{input}"
  appsettings:
    # argument for the app
    skip_bids_validation:
      visible: True
      widget: "check_box"
      checked_value: "--skip_bids_validation"
      unchecked_value: ""
      label: "skip bids validation"
      help: Assume the input dataset is BIDS compliant and skip the validation" 
    participant_label:
      visible: True
      widget: "text_field"
      label: "Participant label"
      help: "A space delimited list of participant identifiers or a single identifier (the sub- prefix can be removed)." 
      pattern: "sub-*"
    # working directory to launch the app
    workdir:
      value: /app
      visible: True
      label: "Working Directory"
      help: "Select your project directory; if that is your home directory, leave as is."
  jobspec:
    # s
    estimated_run_time:
      value: 30
      visible: False
      label: "estimated_run_time"
      help: "estimated_run_time"
    # number of cores
    cpus:
      value: 1
      visible: False
      label: "cpus"
      help: "cpus"
    # ex: ampere:2,VramPerGpu:10G
    gpus:
      value: 0
      visible: False
      label: "gpus"
      help: "gpus"
    # RAM in GB
    ram:
      value: 1
      visible: False
      label: "ram"
      help: "ram"
    # parallel if more than 1
    nbtasks:
      value: 1
      visible: False
      label: "nbtasks"
      help: "nbtasks"
