name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f sources/script/requirements.txt ]; then pip install -r sources/script/requirements.txt; fi
    - name: Delete 'ood' branch if it exists
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git fetch origin
        if git show-ref --verify --quiet refs/remotes/origin/ood; then
          git push origin --delete ood
        fi
    - name: Build application
      run: |
        python --version
        python sources/script/generate_app.py sources/config .

    - name: Commit and push changes to 'ood' branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b ood || git checkout ood
        git add .
        git commit -m "Build and push to ood branch"
        git push origin ood
